apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: frontend
    tier: stage
spec:
  replicas: 2
  selector:
    matchLabels:
     app: frontend
     tier: stage
  template:
    metadata:
      name: app-pod
      lablels:
        app: frontend
        tier: stage
    spec:
      containers:
      - name: helloworld
        image: helloworld
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_USER