apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels:
    env: practice
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        env: practice
    spec:
      containers:
      - name: nginx-2
        image: nginx:1.7.1
  replicas: 2
  selector:
    matchLabels:
      env: practice