apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: ngnix
spec:
  template:
    metadata:
      name: nginx-pod-master
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx-pod-master
        image: nginx:alpine
  replicas: 3
  selector:
    matchLabels:
      app: nginx